services:
  canadian-live-sports:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    environment:
      TZ: America/Vancouver

networks:
  default:
    external: true
    name: proxy
